### ISSUE TITLE
Merge Firebase auth and front-end auth

### ISSUE THREAD

**Issue by akul43** [CSU-Northridge-ARCS-Dev/smart-clothing-app#12]
@GuruVishnu22 @j33l 
Please work together to merge Firebase auth (jeel) and login page (guru).

Feel free to contact me for any questions.

**Comment by akul43** [comment]
@j33l 
Please share .env firebase variable with the team in the slack channel

**Comment by j33l** [comment]
Please review and merge the pull request for merging to main branch. Thanks.
