### ISSUE TITLE
Logout Functionality

### ISSUE THREAD

**Issue by AustinD14** [CSU-Northridge-ARCS-Dev/smart-clothing-app#16]
User Requirements:

- Users should be able to securely log out of their accounts from within the application.
- Users should receive a confirmation message before logging out to prevent accidental logouts.
- Users should be redirected to the login screen.
- Upon logging out, all temporary session data should be cleared to maintain user privacy.

System Requirements:

- The application must provide a clear and accessible option for users to log out, preferably within a user account or settings menu.
- The system should confirm the user's intent to log out with a prompt, allowing them to cancel if the action was unintentional.
- Once a user has logged out, all associated session information should be purged to ensure user data security and prevent unauthorized access.

**Comment by akul43** [comment]
Completed
