### ISSUE TITLE
Display user name during welcome message for home screen

### ISSUE THREAD

**Issue by akul43** [CSU-Northridge-ARCS-Dev/smart-clothing-app#33]
<img width="248" alt="image" src="https://github.com/CSU-Northridge-ARCS-Dev/smart-clothing-app/assets/46544707/fa16aa39-6ebc-40b0-9a40-2c17d9e67aac">

As you can see from the image, the user name is not displayed in the welcome message. "Hello, user"

I recommend checking where the "Hello, user" is displayed in the code, then change that to pull the information from the Firestone. 
Make sure to cover any errors that might occur(for example, check and make sure the user created is valid)

**Comment by j33l** [comment]
**It's already fixed and it will display user name for all new accounts.** Only some accounts which were created before the fix have not registered userName in the Firebase "profile".
