### ISSUE TITLE
AsyncStorage is null

### ISSUE THREAD

**Issue by cfiguer055** [CSU-Northridge-ARCS-Dev/smart-clothing-app#38]
**Running Project**
from AuthStack --> UUID is ... null

**Jest test on App.test.js**
import AsyncStorage from "@react-native-async-storage/async-storage";
error:
[@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

**Comment by j33l** [comment]
It's not a bug, I'm still working on this on [this issue](https://github.com/CSU-Northridge-ARCS-Dev/smart-clothing-app/issues/27)
