### ISSUE TITLE
Figma: UI/UX Design

### ISSUE THREAD

**Issue by akul43** [CSU-Northridge-ARCS-Dev/smart-clothing-app#39]
Continue work on Figma:
https://www.figma.com/file/2rLsjlDrHHVE4YAbP65Mny/Updated-Smart-Clothing-Mobile-Wireframe?type=design&node-id=0-1&mode=design&t=rny1kAMn8gEAM9LC-0

**Comment by A1ya1** [comment]
Hello, can I work on this?

**Comment by akul43** [comment]
Discussing ideas to display biometric data on the app. Referencing the dashboard given from the coaching staff
