### ISSUE TITLE
Edit profile screen

### ISSUE THREAD

**Issue by qtdinh** [CSU-Northridge-ARCS-Dev/smart-clothing-app#43]
Look into working on the edit profile screen. 

Functionalities and requirements include features as listed:
  - Edit full name, which includes first and last name, implement these as mandatory
  - Edit age, gender, and sports. These will be implemented as dropdown boxes.
  - Edit height and weight.
  - The account will be updated through a save button that will provide the user with a form to make any changes. The app will keep track of any changes.
  - Save the changes through a confirmation after inputs have been inserted as prompted. 

Confirm these changes are made in the Firebase.

**Comment by j33l** [comment]
Flow should be something like this...

![Image](https://github.com/CSU-Northridge-ARCS-Dev/smart-clothing-app/assets/45571080/ee83477d-1816-4ee5-a068-4ccccd457dae)
