### ISSUE TITLE
Height and weight validation

### ISSUE THREAD

**Issue by qtdinh** [CSU-Northridge-ARCS-Dev/smart-clothing-app#53]
Ensure and validate that height input and weight input on the data collect modal are in a certain format for data consistency.

Example:
- Height: 5'9
- Weight: (insert number) LBS

Design courtesy of @j33l :
![image](https://github.com/CSU-Northridge-ARCS-Dev/smart-clothing-app/assets/59325099/098201e1-9a1b-4c98-a979-2428d7a42bf6)

**Comment by qtdinh** [comment]
![image](https://github.com/CSU-Northridge-ARCS-Dev/smart-clothing-app/assets/59325099/4ae1839b-1886-4b8e-8aba-3eceec2518cb)

Pretty much done.. but I feel like it would be better to change this into a [slider](https://stackoverflow.com/questions/59782146/how-to-convert-centimeter-value-into-feet-using-multi-slider-in-react-native) in the future.

- Renders differently depending on what unit is chosen. Converts feet/cm into inches and rounds. Kg is converted into lbs and rounded as well.

**Comment by akul43** [comment]
@qtdinh I agree that a slider is better. We could create a low priority ticket for the future.
