### ISSUE TITLE
userReducer Test

### ISSUE THREAD

**Issue by akul43** [CSU-Northridge-ARCS-Dev/smart-clothing-app#58]

**Comment by cfiguer055** [comment]
PASS  __test__/userReducer.test.js
  userReducer
    √ should return the initial state (4 ms)
    √ should handle LOGIN_WITH_EMAIL (38 ms)
    √ should handle SIGNUP_WITH_EMAIL (1 ms)
    √ should handle LOGOUT (1 ms)
    √ should handle UPDATE_PROFILE
    √ should handle UPDATE_USER_METRICS_DATA (1 ms)
    √ should handle UPDATE_EMAIL_SUCCESS

Test Suites: 1 passed, 1 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        1.335 s
Ran all test suites matching /userreducer/i.
