### ISSUE TITLE
Integration Test Between Sign-in and Home Screens

### ISSUE THREAD

**Issue by akul43** [CSU-Northridge-ARCS-Dev/smart-clothing-app#59]

**Comment by cfiguer055** [comment]
PASS  __test__/__integration-test__/__auth-stack-test__/__auth-navigation-test__/SigninToHome.test.js (8.265 s)
   SignUpToHome Integration Test
      √ should navigate from Sign-In to Dashboard (528 ms)
  
  Test Suites: 1 passed, 1 total
  Tests:       1 passed, 1 total
  Snapshots:   0 total
  Time:        8.5 s, estimated 15 s
  Ran all test suites matching /signintohome/i.


 PASS  __test__/__integration-test__/__auth-stack-test__/__auth-navigation-test__/SignupToHome.test.js (7.472 s)
  SignUpToHome Integration Test
    √ should navigate from Sign-In to Sign-Up to Dashboard (758 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        7.692 s, estimated 14 s
Ran all test suites matching /signuptohome/i.
