### ISSUE TITLE
userActions Test

### ISSUE THREAD

**Issue by akul43** [CSU-Northridge-ARCS-Dev/smart-clothing-app#60]

**Comment by cfiguer055** [comment]
PASS  __test__/userActions.test.js
  Async Auth Actions
    √ dispatches LOGOUT action when startLogout is called (4 ms)
    √ logs error when startLogout fails (55 ms)
    √ dispatches UPDATE_PROFILE action when startUpdateProfile is called successfully (15 ms)
    √ logs error when startUpdateProfile fails (8 ms)
    √ logs error and dispatches action when startUpdateUserData fails (13 ms)
    √ logs error when startLoadUserData fails (17 ms)
    √ dispatches UPDATE_USER_METRICS_DATA action when startUpdateUserData is called successfully (20 ms)

Test Suites: 1 passed, 1 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        1.426 s
Ran all test suites matching /useractions/i.
