### ISSUE TITLE
Cannot Navigate to DeviceDevails Screen

### ISSUE THREAD

**Issue by cfiguer055** [CSU-Northridge-ARCS-Dev/smart-clothing-app#63]
My Devices page won't navigate to device detail screen when pressing view buttons for both "Smart Sock" and "Smart Shirt." App does not crash but development-only warning is displayed in terminal.

Smart Sock View:
ERROR  The action 'NAVIGATE' with payload {"name":"DeviceDetails","params":{"id":1}} was not handled by any navigator.
Do you have a screen named 'DeviceDetails'?
If you're trying to navigate to a screen in a nested navigator, see https://reactnavigation.org/docs/nesting-navigators#navigating-to-a-screen-in-a-nested-navigator.
This is a development-only warning and won't be shown in production.

Smart Shirt View:
ERROR  The action 'NAVIGATE' with payload {"name":"DeviceDetails","params":{"id":2}} was not handled by any navigator.
Do you have a screen named 'DeviceDetails'?
If you're trying to navigate to a screen in a nested navigator, see https://reactnavigation.org/docs/nesting-navigators#navigating-to-a-screen-in-a-nested-navigator.
This is a development-only warning and won't be shown in production.

![image](https://github.com/CSU-Northridge-ARCS-Dev/smart-clothing-app/assets/87353706/8a8d8975-5029-492b-9cd7-9453c29aaad9)

**Comment by qtdinh** [comment]
This has already been solved, it will be in the next update.
