### ISSUE TITLE
Figma Design for Coaching Dashboard

### ISSUE THREAD

**Issue by Persian-of-Interest** [CSU-Northridge-ARCS-Dev/smart-clothing-app#87]
Create an initial figma design for the coaching dashboard. Implement mobile responsive version as well.

https://www.figma.com/file/2rLsjlDrHHVE4YAbP65Mny/Updated-Smart-Clothing-Mobile-Wireframe?type=design&node-id=0-1&mode=design&t=yl5M7jpRUmFmN9Ro-0

**Comment by nirvanafan205** [comment]
![landing_page](https://github.com/CSU-Northridge-ARCS-Dev/smart-clothing-app/assets/47827017/7cac4b54-d9e5-49f0-b603-9853191490fc)

First image is in regards of landing page. Welcome touch with a roster of the team, carousel of team highlights, and CSUN moto. Header for greeting the currently logged in user. Settings page and alerts are for editing profile and potential alerts from coaching staff to students. Side navbar is created to depict if it's a student or staff logged in. Nav bar is in the case of athlete login. Only able to see their profiles. Option also includes a link to boracle's website. 

![athletes_profile](https://github.com/CSU-Northridge-ARCS-Dev/smart-clothing-app/assets/47827017/02acc707-eada-464b-8e65-d44b6059bf26)

Second image is if a student would login for their profile. Would show basic information of student athlete. Currently would display graphs such as Intensity and sprint distance. Possible chart to use to display graphs would be chart.js

**Comment by Persian-of-Interest** [comment]
This looks good for starting. I would clean up the colors. Try to make them more consistent. Also think about how this would look on mobile screens as well. Although this won't be part of the native mobile app, it should still be adaptive to mobile devices when accessing from the web on a mobile device.

**Comment by Persian-of-Interest** [comment]
Continued here: https://github.com/CSU-Northridge-ARCS-Dev/coaching-dashboard/issues/1
