### ISSUE TITLE
Implement date selection and hours display on sleep data page

### ISSUE THREAD

**Issue by Persian-of-Interest** [CSU-Northridge-ARCS-Dev/smart-clothing-app#90]
Implement date selection on the sleep data page

Change the graph x axis to display hours of the night instead of 100, 200, etc.

**Comment by qtdinh** [comment]
![image](https://github.com/CSU-Northridge-ARCS-Dev/smart-clothing-app/assets/59325099/17593fd7-583d-44c2-b50a-178eca526b45)
